name: "main branch gatekeeper"

on:
  pull_request:
    branches:
      - main

jobs: 
  check-merge-rules:
    runs-on: ubuntu-latest
    steps:
      - name: verify source branch
        if: github.head_ref != 'dev' && !startsWith(github.head_ref, 'hotfix')
        run: |
          echo "Error: Protected Merge."
          echo "Only 'dev' or 'hotfix' branches can merge into 'main'."
          exit 1


  e2e-tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose -f docker-compose.dev.yml up -d

      - name: Wait for services to be ready
        run: npx wait-on http://localhost:5173 --timeout 60000

      - name: Install dependencies
        run: npm ci

      - name: Run E2E tests
        run: npm run test:e2e

      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.dev.yml down