name: "main branch gatekeeper"

on:
  pull_request:
    branches:
      - main

jobs: 
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: reject pull request if branch is not dev
        if: github.head_ref != 'dev'
        run: |
          echo "FAIL: Pull Requests to 'main' must come from 'dev'."
          echo "Your source is '${{ github.head_ref }}'."
          exit 1

      - name: accept if branch is dev
        if: github.head_ref == 'dev'
        run: echo "Source branch is valid."  
