name: "E2E Tests"

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Start containers
        run: docker compose -f deployment/docker-compose.dev.yml up -d --build

      - name: Wait for services to be ready
        run: npx wait-on http://localhost:5173 --timeout 60000

      - name: Install dependencies
        run: npm ci --prefix web

      - name: Install Playwright Browsers
        run: cd web && npx playwright install --with-deps


      - name: Run createTenant test
        run: cd web && npx playwright test createTenant.spec.ts

      - name: Run createUser test
        run: cd web && npx playwright test createUser.spec.ts

      - name: Run createUserGroup test
        run: cd web && npx playwright test createUserGroup.spec.ts

      - name: Run createSendingProfile test
        run: cd web && npx playwright test createSendingProfile.spec.ts

      - name: Run AlterComplicance test
        run: cd web && npx playwright test AlterComplicance.spec.ts

      - name: Stop containers
        if: always()
        run: docker compose -f deployment/docker-compose.dev.yml down
